# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCodeOfConduct: false
AddContributionDocs: false
AddCopierCI: true
AddGitHubTemplates: true
AddMacToCI: true
AddPrecommit: true
AddWinToCI: false
AnswerStrategy: ask
AuthorEmail: 1806656034@qq.com
AuthorName: hz-xiaxz
Indentation: 4
JuliaMinVersion: '1.10'
License: MIT
PackageName: SCFQFT
PackageOwner: hz-xiaxz
PackageUUID: 89a0a5ea-a54d-5819-a7ed-290244e78af6
RunJuliaNightlyOnCI: true
UseCirrusCI: false
_commit: v0.9.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
