# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCodeOfConduct: false
AddContributionDocs: false
AddCopierCI: false
AddGitHubTemplates: true
AddMacToCI: false
AddPrecommit: true
AddWinToCI: false
AnswerStrategy: ask
Authors: hz-xiaxz <1806656034@qq.com> and contributors
AutoIncludeTests: true
CheckExplicitImports: true
ConfigIndentation: 2
ExplicitImportsChecklist: exclude_all_qualified_accesses_are_public
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: hz-xiaxz
MarkdownIndentation: 2
PackageName: SCFQFT
PackageOwner: hz-xiaxz
PackageUUID: 89a0a5ea-a54d-5819-a7ed-290244e78af6
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.14.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
